from __future__ import annotations

from datetime import datetime
from typing import List, Literal, Optional

from pydantic import BaseModel


class MistakeInsight(BaseModel):
    tag: str
    pattern: str


class WeeklyReviewResponse(BaseModel):
    """
    Module 7 — AI coaching weekly review response.

    source:
      "ai"       — generated by Claude (model_used = claude-haiku-*)
      "fallback" — generated by rule-based fallback (model_used = rule_based_fallback)

    status:
      "success"  — AI path completed successfully
      "fallback" — AI unavailable or failed; rule-based output returned
      "error"    — unexpected error (should not reach client normally)
    """
    # Identifiers
    review_id: str
    account_id: str

    # Period
    from_date: Optional[str] = None    # ISO date e.g. "2026-01-06"
    to_date: Optional[str] = None

    # Generation metadata
    generated_at: str                  # ISO datetime
    model_used: str                    # "claude-haiku-4-5-20251001" | "rule_based_fallback"
    source: str                        # "ai" | "fallback"
    status: str                        # "success" | "fallback" | "error"

    # Review content (same 4 sections as v1)
    summary: str
    top_mistakes: List[MistakeInsight]
    diagnosis: str
    improvement: str


class CoachingReviewListItem(BaseModel):
    """Lightweight summary for the review history list."""
    review_id: str
    account_id: str
    from_date: Optional[str] = None
    to_date: Optional[str] = None
    generated_at: str
    model_used: str
    source: str
    status: str
    # First 120 chars of summary for list preview
    summary_preview: str


class CoachingReviewListResponse(BaseModel):
    account_id: str
    total: int
    reviews: List[CoachingReviewListItem]


class CoachingReviewDetailResponse(BaseModel):
    """Full coaching review including all content sections."""
    review_id: str
    account_id: str
    from_date: Optional[str] = None
    to_date: Optional[str] = None
    generated_at: str
    model_used: str
    source: str
    status: str
    summary: str
    top_mistakes: List[MistakeInsight]
    diagnosis: str
    improvement: str
