from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class MistakeInsight(BaseModel):
    tag: str
    pattern: str


class WeeklyReviewResponse(BaseModel):
    """
    Module 7 — AI coaching weekly review.

    Generated by AICoachService from AccountAnalytics + MistakeAnalyzer outputs.
    All four text fields are AI-generated; the account_id and date fields are
    server-computed from the request parameters.
    """
    account_id: str
    from_date: Optional[str] = None   # ISO date string, e.g. "2026-01-06"
    to_date: Optional[str] = None     # ISO date string

    # AI-generated sections
    summary: str                       # 2-3 sentence week overview
    top_mistakes: List[MistakeInsight] # top recurring mistakes with pattern insight
    diagnosis: str                     # execution / analysis / psychology / risk focus
    improvement: str                   # one actionable priority for next session
